Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 2048
      Handler: org.lambda.service.EC2CheckList
      CodeUri: /home/harshangprajapati/org/tridhyaintuit/projects/ec2insatancelist
      Runtime: java8.al2
      Architectures:
        - x86_64